# - name: check or build ROQ image
#   sudo: yes
#   docker_image: path="../../docker/roq" 
#     name="ubuntu:roqdemo" 
#     state=present 
#   delegate_to: localhost
#   tags:
#     - build-demo-images

# - name: check or build ROQ image
#   sudo: yes
#   docker_image: 
#     path="../../docker/zookeeper"
#     name="debian:zookeeper" 
#     state=present
#   delegate_to: localhost
#   tags:
#     - build-demo-images
#     - build-zookeeper-image

- name: Creates .roq directory
  file: path=~/.roq state=directory mode=777
  delegate_to: localhost
  tags:
    - update-gcm
    - update-hcm

- name: Overwrite GCM default config file
  template: src=GCM.properties.j2 dest='~/.roq/GCM.properties'
  delegate_to: localhost
  tags:
    - update-gcm

- name: Overwrite HCM default config file
  template: src=HCM.properties.j2 dest='~/.roq/HCM.properties'
  delegate_to: localhost
  tags:
    - update-hcm