- name: Creates .roq directory
  file: path=~/.roq state=directory mode=777

- name: Overwrite HCM default config file
  template: src=HCM.properties.j2 dest='~/.roq/HCM.properties'

- name: Copy init.d file
  template: src=roqhcm.j2 dest='/etc/init.d/roqhcm' mode=777

- name: Start HCM component
  service: name=roqhcm state=restarted