-  name: Provision a set of GCM instances
   ec2:
      key_name: '{{ key_path }}'
      assign_public_ip: yes
      instance_type: t2.micro
      group: "{{ security_group }}"
      image: "{{ roq_ami }}"
      wait: yes
      exact_count: "{{ gcm_count }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: subnet-842be7ed
      count_tag:
         Name: GCM
      instance_tags:
         Name: GCM
   register: roqGCM

-  name: Provision a set of HCM instances
   ec2:
      key_name: '{{ key_path }}'
      assign_public_ip: yes
      instance_type: t2.micro
      group: "{{ security_group }}"
      image: "{{ roq_ami }}"
      wait: yes
      exact_count: "{{ hcm_count }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: subnet-842be7ed
      count_tag:
         Name: HCM
      instance_tags:
         Name: HCM
   register: roqHCM

-  name: Provision a set of ZooKeeper instances
   ec2:
      key_name: '{{ key_path }}'
      assign_public_ip: yes
      instance_type: t2.micro
      group: "{{ security_group }}"
      image: "{{ roq_ami }}"
      wait: yes
      exact_count: "{{ zk_count }}"
      region: "{{ aws_region }}"
      vpc_subnet_id: subnet-842be7ed
      count_tag:
         Name: ZK
      instance_tags:
         Name: ZK
   register: roqZK

-  name: Provision two client instances
   ec2:
      key_name: '{{ key_path }}'
      assign_public_ip: yes
      instance_type: t2.micro
      group: "{{ security_group }}"
      image: "{{ roq_ami }}"
      wait: yes
      exact_count: 2
      region: "{{ aws_region }}"
      vpc_subnet_id: subnet-842be7ed
      count_tag:
         Name: CLIENT
      instance_tags:
         Name: CLIENT
   register: roqCLIENT
   tags: 
    - demo

-  name: debug
   debug: msg="GCM private IP {{ hostvars["localhost"]["roqGCM"]["tagged_instances"][0]["private_ip"] }}"

-  name: Wait for ZK SSH to come up
   wait_for: host={{ item.public_ip }}
             port=22
             delay=60
             timeout=320
             state=started
   with_items: roqZK.instances

-  name: Wait for GCM SSH to come up
   wait_for: host={{ item.public_ip }}
             port=22
             delay=60
             timeout=320
             state=started
   with_items: roqGCM.instances

-  name: Wait for HCM SSH to come up
   wait_for: host={{ item.public_ip }}
             port=22
             delay=60
             timeout=320
             state=started
   with_items: roqHCM.instances

-  name: Wait for CLIENT SSH to come up
   wait_for: host={{ item.public_ip }}
             port=22
             delay=60
             timeout=320
             state=started
   with_items: roqCLIENT.instances
   tags:
    - demo

-  name: Add all GCM instances public IPs to GCM group
   add_host: groupname=GCM
             hostname={{ item.0 }}.roq.gcm
             ansible_ssh_host={{ item.1.public_dns_name }}
   with_indexed_items:  hostvars['localhost']['roqGCM']['tagged_instances']

-  name: Add all ZK instances public IPs to ZK group
   add_host: groupname=ZK
             hostname={{ item.0 }}.roq.zk
             ansible_ssh_host={{ item.1.public_dns_name }}
   with_indexed_items:  hostvars['localhost']['roqZK']['tagged_instances']

- name: Add all HCM instances public IPs to HCM group
  add_host: groupname=HCM
            hostname={{ item.0 }}.roq.hcm
            ansible_ssh_host={{ item.1.public_dns_name }}
  with_indexed_items:  hostvars['localhost']['roqHCM']['tagged_instances']

- name: Add all CLIENTS instances public IPs to CLIENT group
  add_host: groupname=CLIENT
            hostname={{ item.0 }}.roq.client
            ansible_ssh_host={{ item.1.public_dns_name }}
  with_indexed_items:  hostvars['localhost']['roqCLIENT']['tagged_instances']
  tags:
    - demo