- name: Add zmq repository
  copy: src=home:fengshuo:zeromq.repo dest=/etc/yum.repos.d/ mode=554

- name: Install required packages
  yum: name="{{item}}" state=latest enablerepo=home_fengshuo_zeromq
  with_items: ['libczmq1', 'libczmq1-devel','java-1.7.0-openjdk-devel', 'gcc-c++', 'libtool', 'autoconf', 'automake', 'git', 'make', 'wget']

- name: Acquire Maven2
  get_url: url=http://www.sai.msu.su/apache//maven/binaries/apache-maven-2.2.1-bin.tar.gz dest=~/apache-maven-2.2.1-bin.tar.gz mode=554 force=yes

- name: Unarchive Maven2
  unarchive: src=~/apache-maven-2.2.1-bin.tar.gz dest=/usr/local copy=no

- name: Create Maven2 links
  shell: "cd /usr/local/; ln -s apache-maven-2.2.1/ maven"
  ignore_errors: True

- name: Add Maven2 entries in .bashrc
  lineinfile: "dest=~/.bashrc line='{{item}}'"
  with_items: ['MAVEN_HOME=/usr/local/maven', 'export MAVEN_HOME', 'PATH=$PATH:$MAVEN_HOME/bin']

- name: Pull ZMQ GIT repository
  git: repo=git://github.com/zeromq/jzmq
       dest="{{jzmq_path}}"
       version=v2.1.3
       ssh_opts="-o StrictHostKeyChecking=no"

- name: Copy custom pom file
  copy: src=pom.xml dest="{{jzmq_path}}/pom.xml" mode=554

- name: Configure and Install ZMQ V2.1.3
  shell: "cd {{jzmq_path}}; {{item}}"
  with_items: ['./autogen.sh', './configure', 'make', 'sudo make install', 'mvn install']
  environment:
       JAVA_HOME: /usr/lib/jvm/jre-1.7.0-openjdk.x86_64

- name: Copy ZK install script
  copy: src=install-zk.sh dest="~/install-zk.sh" mode=554

- name: Install Zookeeper
  shell: "bash ~/install-zk.sh /bin/zookeeperROQ"

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/bin/zookeeperROQ/zookeeper/conf/zoo.cfg
  notify: Restart zookeeper fedora

- name: Start zookeeper
  shell: "/bin/zookeeperROQ/zookeeper/bin/zkServer.sh start"

- name: Pull ROQ GIT repository
  git: repo=git://github.com/roq-messaging/RoQ.git
       dest="{{roq_path}}"
       version=develop
       ssh_opts="-o StrictHostKeyChecking=no"

- name: install ROQ
  shell: "cd {{roq_path}}; mvn install -Dmaven.test.skip=true"
  environment:
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    JAVA_HOME: /usr/lib/jvm/jre-1.7.0-openjdk.x86_64