# The script only supports 64bit architectures

- name: Add zmq repository
  copy: src=home:fengshuo:zeromq.repo dest=/etc/yum.repos.d/ mode=554
  tags:
    - full-install

- name: Install required packages
  yum: name="{{item}}" state=latest enablerepo=home_fengshuo_zeromq
  with_items: ['libczmq1', 'libczmq1-devel','java-1.7.0-openjdk-devel', 'gcc-c++', 'libtool', 'autoconf', 'automake', 'git', 'make', 'wget']
  tags:
    - full-install

- name: Acquire Maven2
  get_url: url=http://www.sai.msu.su/apache//maven/binaries/apache-maven-2.2.1-bin.tar.gz dest=~/apache-maven-2.2.1-bin.tar.gz mode=554 force=yes
  tags:
    - full-install

- name: Unarchive Maven2
  unarchive: src=~/apache-maven-2.2.1-bin.tar.gz dest=/usr/local copy=no
  tags:
    - full-install

- name: Create Maven2 links
  shell: "cd /usr/local/; ln -s apache-maven-2.2.1/ maven"
  ignore_errors: True
  tags:
    - full-install

- name: Add Maven2 entries in .bashrc
  lineinfile: "dest=~/.bashrc line='{{item}}'"
  with_items: ['MAVEN_HOME=/usr/local/maven', 'export MAVEN_HOME', 'PATH=$PATH:$MAVEN_HOME/bin']
  tags:
    - full-install

- name: Pull ZMQ GIT repository
  git: repo=git://github.com/zeromq/jzmq
       dest="{{jzmq_path}}"
       version=v2.1.3
       ssh_opts="-o StrictHostKeyChecking=no"
  tags:
    - full-install

- name: Copy custom pom file
  copy: src=pom.xml dest="{{jzmq_path}}/pom.xml" mode=554
  tags:
    - full-install

- name: Configure and Install ZMQ V2.1.3
  shell: "cd {{jzmq_path}}; {{item}}"
  with_items: ['./autogen.sh', './configure', 'make', 'sudo make install', 'mvn install']
  environment:
       JAVA_HOME: /usr/lib/jvm/jre-1.7.0-openjdk.x86_64
  tags:
    - full-install