# The script only supports 64bit architectures
- name: Set JAVA_HOME environment variable
  lineinfile: dest='/etc/profile' regexp='^#?\s*export JAVA_HOME=(.*)$' line='export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64' state=present

- name: Add zmq repository
  copy: src=home:fengshuo:zeromq.repo dest=/etc/yum.repos.d/ mode=554
  tags:
    - full-install

- name: Install required packages
  yum: name="{{item}}" state=latest enablerepo=home_fengshuo_zeromq
  with_items: ['libczmq1', 'libczmq1-devel','java-1.7.0-openjdk-devel', 'gcc-c++', 'libtool', 'autoconf', 'automake', 'git', 'make', 'wget']
  tags:
    - full-install

- name: Acquire Maven2
  get_url: url=http://www.sai.msu.su/apache//maven/binaries/apache-maven-2.2.1-bin.tar.gz dest=~/apache-maven-2.2.1-bin.tar.gz mode=554 force=yes
  tags:
    - full-install

- name: Unarchive Maven2
  unarchive: src=~/apache-maven-2.2.1-bin.tar.gz dest=/usr/local copy=no
  tags:
    - full-install

- name: Create Maven2 links
  shell: "cd /usr/local/; ln -s apache-maven-2.2.1/ maven"
  ignore_errors: True
  tags:
    - full-install

- name: Add Maven2 entries in .bashrc
  lineinfile: "dest=~/.bashrc line='{{item}}'"
  with_items: ['MAVEN_HOME=/usr/local/maven', 'export MAVEN_HOME', 'PATH=$PATH:$MAVEN_HOME/bin']
  tags:
    - full-install
