- name: Add and Update ZMQ repository
  apt_repository: repo='ppa:chris-lea/zeromq' update_cache=yes state=present
  tags:
    - full-install

- name: Install required packages
  apt: pkg="{{item}}" state=installed
  with_items: ['libzmq1', 'libzmq-dev', 'libzmq-dbg','openjdk-7-jdk', 'maven2', 'g++', 'libtool', 'autoconf', 'automake', 'git', 'make', 'pkg-config', 'wget', 'zookeeper', 'zookeeperd']
  tags:
    - full-install

- name: Pull ZMQ GIT repository
  git: repo=git://github.com/zeromq/jzmq
       dest="{{jzmq_path}}"
       version=v2.1.3
       ssh_opts="-o StrictHostKeyChecking=no"
  tags:
    - full-install

- name: Copy custom pom file
  copy: src=pom.xml dest="{{jzmq_path}}/pom.xml" mode=554
  tags:
    - full-install

- name: Configure and Install ZMQ V2.1.3
  shell: "cd {{jzmq_path}}; {{item}}"
  with_items: ['./autogen.sh', './configure', 'make', 'sudo make install', 'mvn install']
  environment:
       JAVA_HOME: /usr/lib/jvm/java-7-openjdk-i386
  when: ansible_architecture == "i386"
  tags:
    - full-install

# Maven installation duplicated because JAVA_HOME is specific for i386 & x86_64 archi

- name: Configure and Install ZMQ V2.1.3
  shell: "cd {{jzmq_path}}; {{item}}"
  with_items: ['./autogen.sh', './configure', 'make', 'sudo make install', 'mvn install']
  environment:
       JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
  when: ansible_architecture == "x86_64"
  tags:
    - full-install

- name: Overwrite default config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  notify: Restart zookeeper

- name: Start zookeeper
  service: name=zookeeper state=started enabled=yes
  tags:
    - full-install
    - git-update
    - local-update

- name: Pull ROQ from GIT repository
  git: repo=git://github.com/roq-messaging/RoQ.git
       dest="{{roq_path}}"
       version="{{roq_git_branch}}"
       ssh_opts="-o StrictHostKeyChecking=no"
  tags:
    - git-update
    - full-install

- name: Copy ROQ from LOCAL repository
  copy: src="{{roq_local_path}}/" dest="{{roq_path}}" force=yes directory_mode=554 mode=554
  tags:
    - local-update

# ROQ installation duplicated because JAVA_HOME is specific for i386 & x86_64 archi

- name: install ROQ
  shell: "cd {{roq_path}}; mvn install -Dmaven.test.skip=true"
  environment:
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    JAVA_HOME: /usr/lib/jvm/java-7-openjdk-i386
  when: ansible_architecture == "i386"
  tags:
    - git-update
    - local-update
    - full-install

- name: install ROQ
  shell: "cd {{roq_path}}; mvn install -Dmaven.test.skip=true"
  environment:
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
  when: ansible_architecture == "x86_64"
  tags:
    - git-update
    - local-update
    - full-install
