- name: JAVA_HOME Path for this OS in x86_64
  set_fact:
    java_home: /usr/lib/jvm/java-7-openjdk-i386
  when: ansible_architecture == "x86_64"

- name: JAVA_HOME Path for this OS in i386
  set_fact:
    java_home: /usr/lib/jvm/java-7-openjdk-i386
  when: ansible_architecture == "i386"


- name: Add and Update ZMQ repository
  apt_repository: repo='ppa:chris-lea/zeromq' update_cache=yes state=present
  tags:
    - full-install

- name: Install required packages
  apt: pkg="{{item}}" state=installed
  with_items: ['libzmq1', 'libzmq-dev', 'libzmq-dbg','openjdk-7-jdk', 'maven2', 'g++', 'libtool', 'autoconf', 'automake', 'git', 'make', 'pkg-config', 'wget', 'zookeeper', 'zookeeperd']
  tags:
    - full-install
