- name: Set JAVA_HOME environment variable
  lineinfile: dest='/etc/profile' regexp='^#?\s*export JAVA_HOME=(.*)$' line='export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64' state=present
  when: ansible_architecture == "x86_64"

- name: Set JAVA_HOME environment variable
  lineinfile: dest='/etc/profile' regexp='^#?\s*export JAVA_HOME=(.*)$' line='export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386' state=present
  when: ansible_architecture == "i386"

- name: Add and Update ZMQ repository
  apt_repository: repo='ppa:chris-lea/zeromq' update_cache=yes state=present
  tags:
    - full-install

- name: Install required packages
  apt: pkg="{{item}}" state=installed
  with_items: ['libzmq1', 'libzmq-dev', 'libzmq-dbg','openjdk-7-jdk', 'maven2', 'g++', 'libtool', 'autoconf', 'automake', 'git', 'make', 'pkg-config', 'wget', 'zookeeper', 'zookeeperd']
  tags:
    - full-install
