# The script only supports 64bit architectures
- name: JAVA_HOME Path for this OS in i386
  vars:
    java_home: /etc/alternatives/java_sdk_1.7.0

- name: Add zmq repository
  copy: src=home:fengshuo:zeromq.repo dest=/etc/yum.repos.d/ mode=554
  tags:
    - full-install

- name: Install required packages
  yum: name="{{item}}" state=latest enablerepo=home_fengshuo_zeromq
  with_items: ['libczmq1', 'libczmq1-devel','java-1.7.0-openjdk', 'gcc-c++', 'maven2', 'libtool', 'autoconf', 'automake', 'git', 'make', 'wget']
  tags:
    - full-install
