# The script only supports 64bit architectures
- name: Set JAVA_HOME environment variable
  lineinfile: dest='/etc/profile' regexp='^#?\s*export JAVA_HOME=(.*)$' line='export JAVA_HOME=/etc/alternatives/java_sdk_1.7.0' state=present

- name: Add zmq repository
  copy: src=home:fengshuo:zeromq.repo dest=/etc/yum.repos.d/ mode=554
  tags:
    - full-install

- name: Install required packages
  yum: name="{{item}}" state=latest enablerepo=home_fengshuo_zeromq
  with_items: ['libczmq1', 'libczmq1-devel','java-1.7.0-openjdk', 'gcc-c++', 'maven2', 'libtool', 'autoconf', 'automake', 'git', 'make', 'wget']
  tags:
    - full-install
