- name: Pull ZMQ GIT repository
  git: repo=git://github.com/zeromq/jzmq
       dest="{{jzmq_path}}"
       version=v2.1.3
       ssh_opts="-o StrictHostKeyChecking=no"
  tags:
    - full-install

- name: Copy custom pom file
  copy: src=pom.xml dest="{{jzmq_path}}/pom.xml" mode=554
  tags:
    - full-install

- name: Configure and Install ZMQ V2.1.3
  shell: "cd {{jzmq_path}}; {{item}}"
  with_items: ['./autogen.sh', './configure', 'make', 'sudo make install', 'mvn install']
  environment:
       JAVA_HOME: "{{java_home}}"
  tags:
    - full-install